platform :ios, '7.0'
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry'
pod 'MJExtension'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'
pod 'NJKWebViewProgress'
pod 'SDCycleScrollView','~> 1.61'
pod 'SVProgressHUD'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
